// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BerbagiCatatanSwagger.Models;

public partial class catatan
{
    public int id { get; set; }

    public string name { get; set; }

    public int author { get; set; }

    public string description { get; set; }

    public bool _private { get; set; }

    public int like_count { get; set; }

    public virtual user authorNavigation { get; set; }

    public virtual ICollection<bookmark> bookmarks { get; set; } = new List<bookmark>();

    public virtual ICollection<image> images { get; set; } = new List<image>();

    public virtual ICollection<komentar> komentars { get; set; } = new List<komentar>();

    public virtual ICollection<like> likes { get; set; } = new List<like>();
}