// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BerbagiCatatanSwagger.Models;

public partial class like
{
    public int id { get; set; }

    public int catatanId { get; set; }

    public int userId { get; set; }

    public virtual catatan catatan { get; set; }

    public virtual user user { get; set; }
}