// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BerbagiCatatanSwagger.Models;

public partial class refreshToken
{
    public int id { get; set; }

    public string token { get; set; }
}