// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BerbagiCatatanSwagger.Models;

public partial class user
{
    public int id { get; set; }

    public string name { get; set; }

    public string username { get; set; }

    public string password { get; set; }

    public virtual ICollection<bookmark> bookmarks { get; set; } = new List<bookmark>();

    public virtual ICollection<catatan> catatans { get; set; } = new List<catatan>();

    public virtual ICollection<komentar> komentars { get; set; } = new List<komentar>();

    public virtual ICollection<like> likes { get; set; } = new List<like>();
}